Metrics/CyclomaticComplexity:
  Exclude:
    - 'bin/bundle'

Metrics/MethodLength:
  Exclude:
    - 'bin/bundle'

Metrics/PerceivedComplexity:
  Exclude:
    - 'bin/bundle'

Style/IfUnlessModifier:
  Exclude:
    - 'bin/bundle'

Layout/LineLength:
  Exclude:
    - 'bin/bundle'
